services:
  python:
    container_name: fastapi
    hostname: fastapi
    tty: true
    image: "python"
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: .
        target: /fastapi
